app = 'lncurl'
primary_region = 'fra'

[build]

[env]
  # TEMPORARY BASE URL:
  BASE_URL = "https://lncurl.fly.dev"
  #BASE_URL = "https://lncurl.lol"
  DATABASE_URL = "file:/data/lncurl.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "lncurl_data"
  destination = "/data"

[[vm]]
  memory = '512mb'
  cpus = 1
